name: Deploy to Firebase Hosting v2

on:
  push:
    branches:
      - mains

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Write service account key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $GITHUB_WORKSPACE/service-account.json

      - name: Deploy to Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --project vocab-app-a20cc
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json
